homeassistant:
  name: Home
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  elevation: 732
  unit_system: imperial
  time_zone: America/Chicago
  #customize: !include customize.yaml
  customize: !include_dir_merge_named customize


# Includes for better organization
group: !include groups.yaml
automation: !include_dir_list automations
script: !include scripts.yaml
zone: !include zones.yaml
camera: !include cameras.yaml
sensor: !include sensors.yaml
switch: !include switches.yaml
light: !include lights.yaml
binary_sensor: !include binary_sensors.yaml
scene: !include scenes.yaml
device_tracker: !include device_trackers.yaml
notify: !include notifiers.yaml
frontend: !include frontend.yaml
history_graph: !include history_graphs.yaml
cover: !include covers.yaml
media_player: !include media_players.yaml
nest: !include nest.yaml
hangouts: !include hangouts.yaml
intent_script: !include intent_scripts.yaml
google_assistant: !include google_assistant.yaml

updater: # Checks for available updates
discovery: # Discover some devices automatically
history: # Enables support for tracking state changes over time
config: # Enables configuration UI
logbook: # View all events in a logbook
map: # Enables a map showing the location of tracked devices
sun: # for sunset/sunrise automations, etc

#logger:

panel_iframe: # Adds links in sidebar to include helpful resources
  sonoweb:
    title: SonoWeb
    icon: mdi:light-switch
    url: !secret sonoweb_url
  logviewer:
    title: "Log Viewer"
    icon: mdi:playlist-edit
    url: !secret logviewer_url

http: # Enables and configures the web interface
  api_password: !secret api_password
  trusted_networks:
    - 127.0.0.1
    - 10.0.0.0/24
  base_url: !secret base_url_secret
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

recorder: # Database management
  purge_interval: 1
  purge_keep_days: 7

tts: # Text to speech engine selection
  - platform: google

zwave: # Enables z-wave and tells Hass what USB to use
  usb_path: /dev/ttyACM0

mqtt:
  broker: core-mosquitto
  username: !secret mqtt_user
  password: !secret mqtt_pass

google: # For Google Calendar integration
  client_id: !secret hensonhass_google_client_id
  client_secret: !secret hensonhass_google_secret