homeassistant:
  name: Home
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  elevation: 732
  unit_system: imperial
  time_zone: America/Chicago
  customize: !include customize.yaml


# Includes for better organization
group: !include groups.yaml
automation: !include_dir_list automations
script: !include scripts.yaml
zone: !include zones.yaml
camera: !include cameras.yaml
sensor: !include sensors.yaml
switch: !include switches.yaml
light: !include lights.yaml
binary_sensor: !include binary_sensors.yaml
scene: !include scenes.yaml
device_tracker: !include device_trackers.yaml
notify: !include notifiers.yaml
frontend: !include frontend.yaml
history_graph: !include history_graphs.yaml
cover: !include covers.yaml
media_player: !include media_players.yaml
nest: !include nest.yaml
hangouts: !include hangouts.yaml
intent_script: !include intent_scripts.yaml

updater: # Checks for available updates
discovery: # Discover some devices automatically
history: # Enables support for tracking state changes over time
config: # Enables configuration UI
logbook: # View all events in a logbook
map: # Enables a map showing the location of tracked devices
sun: # for sunset/sunrise automations, etc

#logger:

panel_iframe: # Adds links in sidebar to include helpful resources
  # configurator: # For Configurator add-on | web-based config editing
    # title: Configurator
    # icon: mdi:wrench
    # url: !secret configurator_url
  # ide: # For IDE add-on | more robust web-based config editing
    # title: IDE
    # icon: mdi:code-braces
    # url: !secret ide_url
  # terminal: # For Terminal add-on | web-based hass.io terminal
    # title: Terminal
    # icon: mdi:console
    # url: !secret terminal_url
  sonoweb:
    title: SonoWeb
    icon: mdi:light-switch
    url: !secret sonoweb_url
  logviewer:
    title: "Log Viewer"
    icon: mdi:playlist-edit
    url: !secret logviewer_url
  # influxdb:
    # title: InfluxDB
    # icon: mdi:chart-areaspline
    # url: !secret influx_url
  # grafana:
    # title: Grafana
    # icon: mdi:chart-timeline
    # url: !secret grafana_url

# influxdb:
  # host: localhost
  # port: 8086
  # database: !secret influx_database
  # username: !secret influx_username
  # password: !secret influx_password
  # max_retries: 3
  # default_measurement: state

http: # Enables and configures the web interface
  api_password: !secret api_password
  trusted_networks:
    - 127.0.0.1
    - 10.0.0.0/24
  base_url: !secret base_url_secret
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

recorder: # Database management
  purge_interval: 1
  purge_keep_days: 7

tts: # Text to speech engine selection
  - platform: google

zwave: # Enables z-wave and tells Hass what USB to use
  usb_path: /dev/ttyACM0

mqtt:
  broker: core-mosquitto
  username: !secret mqtt_user
  password: !secret mqtt_pass
  # discovery: true
  # discovery_prefix: homeassistant

google: # For Google Calendar integration
  client_id: !secret hensonhass_google_client_id
  client_secret: !secret hensonhass_google_secret

google_assistant:
  project_id: !secret hensonhass_project_id
  #client_id: !secret hensonhass_client_id
  #access_token: !secret hensonhass_access_token
  api_key: !secret hensonhass_api_key
  exposed_domains:
    - light
    - cover
    - switch
  entity_config:
    switch.sonoff_cord_02:
      name: "Over Cabinet Lighting"
      room: "Kitchen"
    switch.bathroom_switch:
      name: "Bathroom Switch"
      room: "Master Bathroom"
    switch.bedroom_switch:
      name: "Bedroom Switch"
      room: "Master Bedroom"
    switch.landscaping_outlet_switch:
      name: "Landscaping Outlet"
      room: "Porch"
    light.peq_lamp:
      name: "Daryl's Lamp"
      room: "Master Bedroom"
    switch.sonoff_cord_01:
      name: "Megan's Lamp"
      room: "Master Bedroom"
    switch.porch_switch:
      name: "Porch Switch"
      room: "Porch"
    light.under_cabinet_lighting:
      name: "Under Cabinet Lighting"
      room: "Kitchen"
    switch.receiver_input_tv:
      expose: false
    switch.receiver_input_xbox:
      expose: false
    switch.receiver_power:
      expose: false
    switch.receiver_power_toggle:
      expose: false
    switch.garage_daryl_switch:
      expose: false
    switch.garage_megan_switch:
      expose: false
    switch.vizio_den_input:
      expose: false
    switch.vizio_den_play_pause:
      expose: false
    switch.vizio_den_power:
      expose: false
    switch.vizio_den_power_toggle_broken:
      expose: false
    switch.xbox_back:
      expose: false
    switch.xbox_backback:
      expose: false
    switch.xbox_backwards:
      expose: false
    switch.xbox_down:
      expose: false
    switch.xbox_forward:
      expose: false
    switch.xbox_hdmi:
      expose: false
    switch.xbox_home:
      expose: false
    switch.xbox_info:
      expose: false
    switch.xbox_left:
      expose: false
    switch.xbox_menu:
      expose: false
    switch.xbox_next:
      expose: false
    switch.xbox_ok:
      expose: false
    switch.xbox_play:
      expose: false
    switch.xbox_power:
      expose: false
    switch.xbox_right:
      expose: false
    switch.xbox_stop:
      expose: false
    switch.xbox_up:
      expose: false