- platform: owntracks
  max_gps_accuracy: 200

- platform: nmap_tracker
  hosts: 10.0.0.0/24
  home_interval: 7
  exclude:
    - 10.0.0.3
  interval_seconds: 30

- platform: google_maps
  username: !secret google_loc_sharing_user
  password: !secret google_loc_sharing_pass