- platform: vizio
  host: 10.0.0.5
  access_token: !secret vizio_auth_token
  name: "Den Vizio"

- platform: plex
  entity_namespace: 'plex'
  #use_custom_entity_ids: true
  use_episode_art: true

# - platform: firetv
  # name: "Bedroom Fire"
  # host: 10.0.0.215
  # adbkey: "/config/android/adbkey"