# - platform: coinmarketcap
  # currency: electroneum
  # dusplay_currency: USD

# - platform: coinmarketcap
  # currency: bitcoin
  # display_currency: USD

- platform: darksky
  api_key: !secret darksky_key
  monitored_conditions:
    - summary
    - icon
    - nearest_storm_distance
    - precip_type
    - precip_probability
    - apparent_temperature
    - dew_point
    - minutely_summary
    - hourly_summary
    - daily_summary
    - temperature_high
    - temperature_low

- platform: plex
  host: !secret htpc_ip
  
- platform: ups
  name: "UPS My Choice"
  username: !secret ups_user
  password: !secret ups_pass

# - platform: fedex
  # name: "FedEx Manager"
  # username: !secret fedex_user
  # password: !secret fedex_pass
  # update_interval: '00:15:00'

- platform: speedtest
  minute: 0
  hour:
    - 0
    - 4
    - 8
    - 12
    - 16
    - 20
  monitored_conditions:
    - ping
    - download
    - upload

- platform: google_wifi

- platform: transmission
  host: !secret htpc_ip
  port: 428
  username: !secret transmission_user
  password: !secret transmission_pass
  monitored_variables:
    - 'current_status'
    - 'download_speed'
    - 'upload_speed'
    - 'active_torrents'

- platform: mqtt
  state_topic: "owntracks/mixpix405/2xl"
  name: "Daryl's Battery"
  unit_of_measurement: "%"
  value_template: '{{ value_json.batt }}'

- platform: mqtt
  state_topic: "owntracks/mixpix405/megans_xl"
  name: "Megan's Battery"
  unit_of_measurement: "%"
  value_template: '{{ value_json.batt }}'

- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /home
    - type: memory_use_percent
    - type: ipv4_address
      arg: eth0
    - type: processor_use
    - type: last_boot
    - type: since_last_boot

- platform: mqtt
  state_topic: "smartthings/PEQ Motion Sensor/temperature/state"
  name: "Kitchen Temp"
  unit_of_measurement: "°F"

- platform: mqtt
  state_topic: "smartthings/PEQ Door Sensor/temperature/state"
  name: "Bathroom Temp"
  unit_of_measurement: "°F"

- platform: mqtt
  name: "Kitchen Motion"
  state_topic: "smartthings/PEQ Motion Sensor/motion/state"
  payload_on: "active"
  payload_off: "inactive"
  # device_class: "motion"

- platform: mqtt
  name: "Bathroom Door"
  state_topic: "smartthings/PEQ Door Sensor/contact/state"
  # payload_on: "closed"
  # payload_off: "open"
  # device_class: "opening"

- platform: mqtt
  name: "Daryl's Garage Door"
  state_topic: "smartthings/Daryl's Garage Door Sensor/contact/state"
  payload_on: "open"
  payload_off: "closed"
  # device_class: "opening"

- platform: mqtt
  name: "Megan's Garage Door"
  state_topic: "smartthings/Megan's Garage Door Sensor/contact/state"
  payload_on: "open"
  payload_off: "closed"
  # device_class: "opening"

- platform: cert_expiry
  host: !secret duck_domain
  port: !secret duck_port
  name: "SSL Cert"

# - platform: xbox_live
  # api_key: !secret xboxapi_key
  # xuid:
    # - !secret xbox_uid

# - platform: lastfm
  # api_key: 2f812625c3ae0506f71e999d2908f572
  # users:
    # - mixpix405

- platform: google_travel_time
  name: "Time to Home for Daryl"
  api_key: !secret hensonhass_api_key
  origin: device_tracker.mixpix405_2xl
  destination: zone.home

- platform: google_travel_time
  name: "Time to Home for Megan"
  api_key: !secret hensonhass_api_key
  origin: device_tracker.mixpix405_megans_xl
  destination: zone.home

#- platform: pi_hole

- platform: command_line
  name: log_db_file_size
  command: "du -m /config/home-assistant_v2.db | cut -f1"
  unit_of_measurement: "MB"
  value_template: '{{ value | int - 1 }}'

- platform: command_line
  name: ipinfo_city
  command: "curl http://10.0.0.2/city.txt"

###################
# HTPC Monitoring #
###################
# - platform: mqtt
  # state_topic: "HTPC/freememory"
  # name: "HTPC freememory"

#############
# Templates #
#############
- platform: template
  sensors:
    ### Staples ###
    htpc:
      friendly_name: "HTPC"
      value_template: "{% if is_state('device_tracker.htpclan', 'home') %}Online{% else %}Offline{% endif %}"
    range_extender:
      friendly_name: "Range Extender"
      value_template: "{% if is_state('device_tracker.tlwa855relan', 'home') %}Online{% else %}Offline{% endif %}"
    st_hub:
      friendly_name: "SmartThings Hub"
      value_template: "{% if is_state('device_tracker.st24fd5b00000037a4lan', 'home') %}Online{% else %}Offline{% endif %}"
    nest:
      friendly_name: "Nest Thermostat"
      value_template: "{% if is_state('device_tracker.09aa01ac25160s7klan', 'home') %}Online{% else %}Offline{% endif %}"
    retropie:
      friendly_name: "RetroPie"
      value_template: "{% if is_state('device_tracker.retropielan', 'home') %}Online{% else %}Offline{% endif %}"
    daryl_laptop:
      friendly_name: "Daryl's Laptop"
      value_template: "{% if is_state('device_tracker.darylt580', 'home') %}Online{% else %}Offline{% endif %}"
    chromebook_lenovo:
      friendly_name: "Lenovo Chromebook"
      value_template: "{% if is_state('device_tracker.chromebook_lenovo', 'home') %}Online{% else %}Offline{% endif %}"
    sonoff_01:
      friendly_name: "Sonoff 01"
      value_template: "{% if is_state('device_tracker.sonoff_01', 'home') %}Online{% else %}Offline{% endif %}"
    sonoff_02:
      friendly_name: "Sonoff 02"
      value_template: "{% if is_state('device_tracker.sonoff_02', 'home') %}Online{% else %}Offline{% endif %}"
    wyze_cam:
      friendly_name: "Wyze Cam"
      value_template: "{% if is_state('device_tracker.wyze_cam', 'home') %}Online{% else %}Offline{% endif %}"
    ### Cast Devices ###
    ghome_kitchen:
      friendly_name: "GHome Kitchen"
      value_template: "{% if is_state('device_tracker.googlehomelan', 'home') %}Online{% else %}Offline{% endif %}"
    ghome_mini_bedroom:
      friendly_name: "GHome Mini (Bedroom)"
      value_template: "{% if is_state('device_tracker.e4f0421cb224', 'home') %}Online{% else %}Offline{% endif %}"
    ghome_mini_bathroom:
      friendly_name: "GHome Mini (Bathroom)"
      value_template: "{% if is_state('device_tracker.ghome_bathroom', 'home') %}Online{% else %}Offline{% endif %}"
    cast_bedroom:
      friendly_name: "Bedroom Chromecast"
      value_template: "{% if is_state('device_tracker.6cadf82677a2', 'home') %}Online{% else %}Offline{% endif %}"
    dat_dongle:
      friendly_name: "Dat Dongle"
      value_template: "{% if is_state('device_tracker.chromecastlan', 'home') %}Online{% else %}Offline{% endif %}"
    ### Mobiles ###
    sawyers_tablet:
      friendly_name: "Sawyer's Tablet"
      value_template: "{% if is_state('device_tracker.sawyers_tablet', 'home') %}Online{% else %}Offline{% endif %}"
    audreys_tablet:
      friendly_name: "Audrey's Tablet"
      value_template: "{% if is_state('device_tracker.audreys_tablet', 'home') %}Online{% else %}Offline{% endif %}"
    daryl_xl_nmap:
      friendly_name: "Daryl's XL"
      value_template: "{% if is_state('device_tracker.daryl_2xl', 'home') %}Online{% else %}Offline{% endif %}"
    daryl_charging:
      friendly_name: "Daryl Charging"
      value_template: "{% if is_state('binary_sensor.daryl_charging', 'on') %}Charging{% else %}Not Charging{% endif %}"
      icon_template: "{% if is_state('binary_sensor.daryl_charging', 'on') %}mdi:power-plug{% else %}mdi:power-plug-off{% endif %}"
    daryls_battery_dyn:
      friendly_name: "Daryl's XL"
      unit_of_measurement: "%"
      value_template: "{{states.sensor.daryls_battery.state}}"
      icon_template: "{%- if states.sensor.daryls_battery.state >= '95' %}mdi:battery{%- elif states.sensor.daryls_battery.state == '100' %}mdi:battery{%- elif states.sensor.daryls_battery.state == '' %}mdi:battery-unknown{%- elif states.sensor.daryls_battery.state <= '15' %}mdi:battery-outline{% else %}mdi:battery-{{(states.sensor.daryls_battery.state|float / 10)|round*10}}{%- endif %}"
    daryl_watch:
      friendly_name: "Daryl's Watch"
      value_template: "{% if is_state('device_tracker.android5486ce199fee9d90lan', 'home') %}Online{% else %}Offline{% endif %}"
    megan_nmap: # updated
      friendly_name: "Megan's Pixel 2"
      value_template: "{% if is_state('device_tracker.megans_pixel_2', 'home') %}Online{% else %}Offline{% endif %}"
    megan_charging:
      friendly_name: "Megan Charging"
      value_template: "{% if is_state('binary_sensor.megan_charging', 'on') %}Charging{% else %}Not Charging{% endif %}"
      icon_template: "{% if is_state('binary_sensor.megan_charging', 'on') %}mdi:power-plug{% else %}mdi:power-plug-off{% endif %}"
    megans_battery_dyn:
      friendly_name: "Megan's Pixel 2"
      unit_of_measurement: "%"
      value_template: "{{states.sensor.megans_battery.state}}"
      icon_template: "{%- if states.sensor.megans_battery.state >= '95' %}mdi:battery{%- elif states.sensor.megans_battery.state == '100' %}mdi:battery{%- elif states.sensor.megans_battery.state == '' %}mdi:battery-unknown{%- elif states.sensor.megans_battery.state <= '15' %}mdi:battery-outline{% else %}mdi:battery-{{(states.sensor.megans_battery.state|float / 10)|round*10}}{%- endif %}"
    ### Other people's mobiles ###
    beckys_phone:
      friendly_name: "Mom's Phone"
      value_template: "{% if is_state('device_tracker.moms_phone', 'home') %}Online{% else %}Offline{% endif %}"
    josh_iphone:
      friendly_name: "Josh's iPhone X"
      value_template: "{% if is_state('device_tracker.josh_iphone_x', 'home') %}Online{% else %}Offline{% endif %}"
    josh_apple_watch:
      friendly_name: "Josh's Apple Watch"
      value_template: "{% if is_state('device_tracker.josh_apple_watch', 'home') %}Online{% else %}Offline{% endif %}"
    ### Other Sensors ###
    xbox_one:
      friendly_name: "XBOne"
      value_template: "{% if is_state('device_tracker.xboxonelan', 'home') %}Online{% else %}Offline{% endif %}"
    bathroom_door_status:
      friendly_name: "Bathroom Door"
      value_template: "{% if is_state('sensor.bathroom_door', 'open') %}closed{% else %}open{% endif %}"
      icon_template: "{% if is_state('sensor.bathroom_door_status', 'open') %}mdi:door-open{% else %}mdi:door-closed{% endif %}"
    daryl_garage_status:
      friendly_name: "Daryl's Garage Door"
      value_template: "{% if is_state('sensor.daryls_garage_door', 'open') %}open{% else %}closed{% endif %}"
      icon_template: "{% if is_state('sensor.daryls_garage_door', 'open') %}mdi:garage-open{% else %}mdi:garage{% endif %}"
    megan_garage_status:
      friendly_name: "Megan's Garage Door"
      value_template: "{% if is_state('sensor.megans_garage_door', 'open') %}open{% else %}closed{% endif %}"
      icon_template: "{% if is_state('sensor.megans_garage_door', 'open') %}mdi:garage-open{% else %}mdi:garage{% endif %}"
    megan_explorer:
      friendly_name: "Megan's Explorer"
      value_template: "{% if is_state('device_tracker.megan_explorer', 'home') %}Online{% else %}Offline{% endif %}"
    htpc_pia:
      friendly_name: "PIA"
      value_template: "{% if is_state('sensor.ipinfo_city', 'Gadsden') %}Disconnected{% else %}Protected{% endif %}"
    den_tv_source:
      friendly_name: "Den TV Source"
      value_template: '{{ states.media_player.den_vizio.attributes.source }}'