# Transmission Turtle
# - platform: transmission
  # host: !secret htpc_ip
  # port: 428
  # name: "Transmission Turtle"
  # username: !secret transmission_user
  # password: !secret transmission_pass

# - platform: deluge
  # host: 10.0.0.2
  # username : daryl
  # password : 4ndr0idG33k

# Broadlink RM Mini 3
- platform: broadlink
  host: 10.0.0.62
  mac: '34:EA:34:51:20:25'
  switches:
    #### XBOX SWITCHES ###
    xbox_power:
      friendly_name: "XBOX POWER"
      command_on: 'JgBQAAABKJQTEhMTExITEhQSExIUEhM3ExMTEhMSFDcTNxQSEzcTOBMSEzcUEhM3FBITNxMTExITNxQSEzcUEhM3ExMTNxM3FAAFngABKUoTAA0FAAAAAAAAAAA='
      command_off: 'JgBQAAABKJQTEhQSExIUEhMSFBITEhM3FBITEhQSEzcUNxMSEzgTNxM3FBITEhQ3ExITOBMSExIUEhM3FDcTEhM3FBITNxQ3EwAFnwABKUkTAA0FAAAAAAAAAAA='
    xbox_home:
      friendly_name: "XBOX HOME"
      command_on: 'JgBQAAABKpIVDxURFRAVDxURFRAUEBU2FBAVERQRFDUVNRURFDUVNhQRFBEUNRURFBEVNRQ1FREUNhQ2FRAUNhU1FBEVEBQ2FQAFbwABK0cVAA0FAAAAAAAAAAA='
      command_off: 'JgBQAAABKpIVDxURFRAVDxURFRAUEBU2FBAVERQRFDUVNRURFDUVNhQRFBEUNRURFBEVNRQ1FREUNhQ2FRAUNhU1FBEVEBQ2FQAFbwABK0cVAA0FAAAAAAAAAAA='
    xbox_ok:
      friendly_name: "XBOX OK"
      command_on: 'JgBQAAABKJQUERMSExITEhMSExIUERM3FBETEhMSFDYSOBMSEjgTNxMSEzcUERMSEhMUNhITFBETNxMSEzcUNhM3ExMSNxM3FAAFcQABJ0oUAA0FAAAAAAAAAAA='
      command_off: 'JgBQAAABKJQUERMSExITEhMSExIUERM3FBETEhMSFDYSOBMSEjgTNxMSEzcUERMSEhMUNhITFBETNxMSEzcUNhM3ExMSNxM3FAAFcQABJ0oUAA0FAAAAAAAAAAA='
    xbox_up:
      friendly_name: "XBOX UP"
      command_on: 'JgBQAAABKpIVEBUQFRAVEBUQFRAVEBU1FRAVEBUQFTUVNRUQFTUVNRUQFTUVNRU1FTUVEBUQFRAVNRUQFRAVEBUQFTUVNRU1FQAFbwABK0cVAA0FAAAAAAAAAAA='
      command_off: 'JgBQAAABKpIVEBUQFRAVEBUQFRAVEBU1FRAVEBUQFTUVNRUQFTUVNRUQFTUVNRU1FTUVEBUQFRAVNRUQFRAVEBUQFTUVNRU1FQAFbwABK0cVAA0FAAAAAAAAAAA='
    xbox_down:
      friendly_name: "XBOX DOWN"
      command_on: 'JgBQAAABKpIVEBQRFBEVEBQRFBEVEBQ2FRAUERUQFTUUNhQRFTYTNhU1FTUUNhU1FTUUERUQFRETERUQFRETERUQFTUVNRU1FQAFcAABKkgVAA0FAAAAAAAAAAA='
      command_off: 'JgBQAAABKpIVEBQRFBEVEBQRFBEVEBQ2FRAUERUQFTUUNhQRFTYTNhU1FTUUNhU1FTUUERUQFRETERUQFRETERUQFTUVNRU1FQAFcAABKkgVAA0FAAAAAAAAAAA='
    xbox_left:
      friendly_name: "XBOX LEFT"
      command_on: 'JgBQAAABK5IUEBUQFREUEBUQFREUEBU2FBAVEBURFDUVNRUQFTUVNhQQFRAVERQQFRAVNRUQFREUNRU1FTYUNRU1FRAVNRU2FAAFbwABK0cVAA0FAAAAAAAAAAA='
      command_off: 'JgBQAAABK5IUEBUQFREUEBUQFREUEBU2FBAVEBURFDUVNRUQFTUVNhQQFRAVERQQFRAVNRUQFREUNRU1FTYUNRU1FRAVNRU2FAAFbwABK0cVAA0FAAAAAAAAAAA='
    xbox_right:
      friendly_name: "XBOX RIGHT"
      command_on: 'JgBQAAABKpIVEBUQFBEVEBUQFBEVEBU1FRAVEBQRFTUUNhUQFTUVNRU1FRAVEBURFBAVNRQRFRAVERM2FTUVNRU1FREUNRU1FQAFbwABKkgVAA0FAAAAAAAAAAA='
      command_off: 'JgBQAAABKpIVEBUQFBEVEBUQFBEVEBU1FRAVEBQRFTUUNhUQFTUVNRU1FRAVEBURFBAVNRQRFRAVERM2FTUVNRU1FREUNRU1FQAFbwABKkgVAA0FAAAAAAAAAAA='
    xbox_back:
      friendly_name: "XBOX BACK"
      command_on: 'JgBQAAABK5MVEBUQFRAVEBYQFRAVEBU1FRAVEBYQFTUVNRUQFTUWNBY1FTUVEBUQFRAWNBYQFRAVEBUQFTUWNRU1FRAVNRU1FQAFggABKkoVAA0FAAAAAAAAAAA='
      command_off: 'JgBQAAABK5MVEBUQFRAVEBYQFRAVEBU1FRAVEBYQFTUVNRUQFTUWNBY1FTUVEBUQFRAWNBYQFRAVEBUQFTUWNRU1FRAVNRU1FQAFggABKkoVAA0FAAAAAAAAAAA='
    xbox_hdmi:
      friendly_name: "XBOX HDMI"
      command_on: 'JgBQAAABK5EVEBURFBAVEBURFBAVEBU1FRAVERQQFTYUNRURFDUVNRURFDUVNhQQFREUNRURFBEUNhQRFBAVNhQ1FREUNRU1FQAFcQABKkcVAA0FAAAAAAAAAAA='
      command_off: 'JgBQAAABK5EVEBURFBAVEBURFBAVEBU1FRAVERQQFTYUNRURFDUVNRURFDUVNhQQFREUNRURFBEUNhQRFBAVNhQ1FREUNRU1FQAFcQABKkcVAA0FAAAAAAAAAAA='
    xbox_menu:
      friendly_name: "XBOX MENU"
      command_on: 'JgBQAAABKZIVEBUQFRAVEBUQFRAVEBU1FRAVEBUQFTUVNRUQFTUVNRU1FTUVNRU1FRAVNRU1FRAVEBURFBAVEBU1FRAVERQ1FQAFbgABKkgVAA0FAAAAAAAAAAA='
      command_off: 'JgBQAAABKZIVEBUQFRAVEBUQFRAVEBU1FRAVEBUQFTUVNRUQFTUVNRU1FTUVNRU1FRAVNRU1FRAVEBURFBAVEBU1FRAVERQ1FQAFbgABKkgVAA0FAAAAAAAAAAA='
    xbox_info:
      friendly_name: "XBOX INFO"
      command_on: 'JgBQAAABK5EWEBQQFg8WEBQQFg8WEBQ1FhAUEBYPFjQWNBUQFjUUNRYQFDUWNBY1FBAWNRQ1FhAUNRYQFBAWDxY0Fg8WDxU1FgAFbwABK0cWAA0FAAAAAAAAAAA='
      command_off: 'JgBQAAABK5EWEBQQFg8WEBQQFg8WEBQ1FhAUEBYPFjQWNBUQFjUUNRYQFDUWNBY1FBAWNRQ1FhAUNRYQFBAWDxY0Fg8WDxU1FgAFbwABK0cWAA0FAAAAAAAAAAA='
    xbox_play:
      friendly_name: "XBOX PLAY"
      command_on: 'JgBQAAABKpIVEBUQFRETERUQFRETERU1FBEVEBUREzYVNRUQFTUVNRQRFRAVEBUQFTUVNRU1FRAVNRU1FTUVNRUQFREUEBU1FQAFagABKkgVAA0FAAAAAAAAAAA='
      command_off: 'JgBQAAABKpIVEBUQFRETERUQFRETERU1FBEVEBUREzYVNRUQFTUVNRQRFRAVEBUQFTUVNRU1FRAVNRU1FTUVNRUQFREUEBU1FQAFagABKkgVAA0FAAAAAAAAAAA='
    xbox_backwards:
      friendly_name: "XBOX FAST BACKWARD"
      command_on: 'JgBQAAABKpIVDxURFBEVDxURFBEVDxU2FQ8VEBURFDUVNRUQFTUVNhQ1FREUNRURFDUVERQRFBAVERQ1FREUNRURFDUVNhQ2FAAFbgABKkgUAA0FAAAAAAAAAAA='
      command_off: 'JgBQAAABKpIVDxURFBEVDxURFBEVDxU2FQ8VEBURFDUVNRUQFTUVNhQ1FREUNRURFDUVERQRFBAVERQ1FREUNRURFDUVNhQ2FAAFbgABKkgUAA0FAAAAAAAAAAA='
    xbox_forward:
      friendly_name: "XBOX FAST FORWARD"
      command_on: 'JgBQAAABK5EVEBUQFREUEBUQFREUEBU2FBAVEBURFDUVNRUQFTUVNhQQFRAVNRUQFTUVEBURFBAVNhQ1FREUNRURFDUVNRU2FAAFbwABK0gUAA0FAAAAAAAAAAA='
      command_off: 'JgBQAAABK5EVEBUQFREUEBUQFREUEBU2FBAVEBURFDUVNRUQFTUVNhQQFRAVNRUQFTUVEBURFBAVNhQ1FREUNRURFDUVNRU2FAAFbwABK0gUAA0FAAAAAAAAAAA='
    xbox_stop:
      friendly_name: "XBOX STOP"
      command_on: 'JgBQAAABKpIUERUQFBAVERQRFBAVERQ1FREUERQQFTYUNhQRFDYUNRU2FBAVERQ1FTYVDxURFBEVDxU2FTUUERUPFTYVNRQ1FQAFbgABK0gUAA0FAAAAAAAAAAA='
      command_off: 'JgBQAAABKpIUERUQFBAVERQRFBAVERQ1FREUERQQFTYUNhQRFDYUNRU2FBAVERQ1FTYVDxURFBEVDxU2FTUUERUPFTYVNRQ1FQAFbgABK0gUAA0FAAAAAAAAAAA='
    xbox_next:
      friendly_name: "XBOX FAST NEXT"
      command_on: 'JgBYAAABKZUTEhQRExITEhMTExIUERQ2ExITEhQSEzcUNhQRFDQVNxQSEzcUERM3EzcUERQSExITNxQRFDYTExMSFDYUNhM3EwAFhAABKUsUAAxSAAEqShQADQU='
      command_off: 'JgBYAAABKZUTEhQRExITEhMTExIUERQ2ExITEhQSEzcUNhQRFDQVNxQSEzcUERM3EzcUERQSExITNxQRFDYTExMSFDYUNhM3EwAFhAABKUsUAAxSAAEqShQADQU='
    xbox_backback:
      friendly_name: "XBOX FAST BACK"
      command_on: 'JgBQAAABKZMVEBUREhIVEBUREhITEhU1FRAVEBUQEzcVNRUQFTUVNRM3FTUVEBU1FTUVEBUQFREUEBUQFTUWDxURFDUWNBY1FAAFcAABK0cVAA0FAAAAAAAAAAA='
      command_off: 'JgBQAAABKZMVEBUREhIVEBUREhITEhU1FRAVEBUQEzcVNRUQFTUVNRM3FTUVEBU1FTUVEBUQFREUEBUQFTUWDxURFDUWNBY1FAAFcAABK0cVAA0FAAAAAAAAAAA='
    #### TV SWITCHES ###
    vizio_den_play_pause:
      friendly_name: "Vizio Play/Pause"
      command_on: 'JgBYAAABKZMTExMSEzcTEhMSExISExMTEjcTNxIUETgSNxM4EjgSOBIUERQSOBITEhMSExI4EhMSOBI4EhMSNxM4EjgSFBE4EgAFDwABKkgUAAxIAAEqSBUADQU='
      command_off: 'JgBYAAABKZMTExMSEzcTEhMSExISExMTEjcTNxIUETgSNxM4EjgSOBIUERQSOBITEhMSExI4EhMSOBI4EhMSNxM4EjgSFBE4EgAFDwABKkgUAAxIAAEqSBUADQU='
    vizio_den_power_toggle_broken:
      friendly_name: "Vizio Power Toggle broken"
      command_on: 'JgBYABQRFBIUNhQRFBEUERQRFBEUNhQ2FBEUNhQ2FDYUNhQ2FBIUERQRFDYUERQRFBEUEhM2FDYUNhQSFDYUNhQ1FTUUAAUNAAEqSBQABAsLAAgzAAEpSRQADQU='
      command_off: 'JgBYABQRFBIUNhQRFBEUERQRFBEUNhQ2FBEUNhQ2FDYUNhQ2FBIUERQRFDYUERQRFBEUEhM2FDYUNhQSFDYUNhQ1FTUUAAUNAAEqSBQABAsLAAgzAAEpSRQADQU='
    vizio_den_power:
      friendly_name: "Vizio Power"
      command_on: 'AAAAbQAiAAIBVwCsABUAFgAVABYAFQBBABUAFgAVABYAFQAWABUAFgAVABYAFQBBABUAQQAVABYAFQBBABUAQQAVAEEAFQBBABUAQQAVABYAFQBBABUAFgAVAEEAFQAWABUAQQAVABYAFQAWABUAQQAVABYAFQBBABUAFgAVAEEAFQAWABUAQQAVAEEAFQaJAVcAVgAVDpQ='
      command_off: 'AAAAbQAiAAIBVwCsABUAFgAVABYAFQBBABUAFgAVABYAFQAWABUAFgAVABYAFQBBABUAQQAVABYAFQBBABUAQQAVAEEAFQBBABUAQQAVAEEAFQAWABUAQQAVABYAFQAWABUAQQAVABYAFQAWABUAFgAVAEEAFQAWABUAQQAVAEEAFQAWABUAQQAVAEEAFQaJAVcAVgAVDpQ='
    vizio_den_input:
      friendly_name: "Vizio Input"
      command_on: 'AAAAbQAiAAIBVwCsABUAFgAVABYAFQBBABUAFgAVABYAFQAWABUAFgAVABYAFQBBABUAQQAVABYAFQBBABUAQQAVAEEAFQBBABUAQQAVAEEAFQAWABUAFgAVAEEAFQAWABUAFgAVAEEAFQAWABUAFgAVAEEAFQBBABUAFgAVAEEAFQBBABUAFgAVAEEAFQaJAVcAVgAVDpQ='
      command_off: 'AAAAbQAiAAIBVwCsABUAFgAVABYAFQBBABUAFgAVABYAFQAWABUAFgAVABYAFQBBABUAQQAVABYAFQBBABUAQQAVAEEAFQBBABUAQQAVAEEAFQAWABUAFgAVABYAFQAWABUAFgAVABYAFQBBABUAFgAVAEEAFQBBABUAQQAVAEEAFQBBABUAQQAVABYAFQaJAVcAVgAVDpQ='
    #### AVR SWITCHES ###
    receiver_power:
      friendly_name: "AVR Power"
      command_on: 'AAAAbQAAACAACgAeAAoARgAKAB4ACgAeAAoAHgAKAEYACgAeAAoAHgAKAB4ACgAeAAoARgAKAEYACgBGAAoAHgAKAB4ACgZ5AAoAHgAKAEYACgAeAAoAHgAKAB4ACgAeAAoARgAKAEYACgBGAAoARgAKAB4ACgAeAAoAHgAKAEYACgBGAAoGeQ=='
      command_off: 'AAAAbQAAACAACgAeAAoARgAKAB4ACgAeAAoAHgAKAB4ACgBGAAoAHgAKAB4ACgAeAAoARgAKAEYACgBGAAoAHgAKAB4ACgZ5AAoAHgAKAEYACgAeAAoAHgAKAB4ACgBGAAoAHgAKAEYACgBGAAoARgAKAB4ACgAeAAoAHgAKAEYACgBGAAoGeQ=='
    receiver_power_toggle:
      friendly_name: "AVR Power Toggle"
      command_on: 'JgA2AW84Dw0PDQ8oDw0PKQ8NDikPDQ8NDygPDQ8NDygPKQ8NDw0ODQ8NDw0PDQ8NDg0PKQ8NDygPDQ8NDw0OKQ8NDykODQ8NDw0PDQ8NDg0PDg4NDw0OKQ8NDw0PDQ4pDw0PDQ8NDgACdgoABzRvOA8NDw0PKA8NDykPDQ4pDw0PDQ8oDw0PDQ8oDykPDQ8NDg0PDQ8NDw0ODQ8NDykPDQ4pDw0PDQ8NDikPDQ8pDg0PDQ8NDw0PDA8NDw0PDQ8NDikPDQ8NDw0OKQ8NDw0PDA8ACbRvOA8NDw0PKA8NDykPDQ4pDw0PDQ8oDw0PDQ8oDykPDQ8NDg0PDQ8NDw0ODQ8NDykPDQ4pDw0PDQ8NDikPDQ8oDw0PDQ8NDw0ODQ8NDw0PDQ8NDikPDQ8NDwwPKQ8NDw0ODQ8ADQUAAA=='
      command_off: 'JgA2AW84Dw0PDQ8oDw0PKQ8NDikPDQ8NDygPDQ8NDygPKQ8NDw0ODQ8NDw0PDQ8NDg0PKQ8NDygPDQ8NDw0OKQ8NDykODQ8NDw0PDQ8NDg0PDg4NDw0OKQ8NDw0PDQ4pDw0PDQ8NDgACdgoABzRvOA8NDw0PKA8NDykPDQ4pDw0PDQ8oDw0PDQ8oDykPDQ8NDg0PDQ8NDw0ODQ8NDykPDQ4pDw0PDQ8NDikPDQ8pDg0PDQ8NDw0PDA8NDw0PDQ8NDikPDQ8NDw0OKQ8NDw0PDA8ACbRvOA8NDw0PKA8NDykPDQ4pDw0PDQ8oDw0PDQ8oDykPDQ8NDg0PDQ8NDw0ODQ8NDykPDQ4pDw0PDQ8NDikPDQ8oDw0PDQ8NDw0ODQ8NDw0PDQ8NDikPDQ8NDwwPKQ8NDw0ODQ8ADQUAAA=='
    receiver_input_tv:
      friendly_name: "AVR Input TV"
      command_on: 'JgDQAA4AAapuNhANDg0PKA8NDigPDQ8oDg0PDQ4pDg0PDQ4pDikODQ8NDg0PDQ4NDw0ODQ8NDikODQ8oDw0ODQ8NDg0PKA8NDg0PKA8MDygPKA8NDikODQ8NDg0PDQ4pDikODQ8NDikODQ8ACX9uNw4NDw0OKQ4NDygPDA8oDw0ODQ8oDw0ODQ8oDygPDQ4NDw0ODQ8NDg0PDQ4NDygPDQ4pDg0PDQ4NDw0OKQ4NDw0OKA8NDikOKQ4NDygPDQ4NDw0ODQ8oDygPDQ4NDygPDQ4ADQUAAAAAAAAAAA=='
      command_off: 'JgDQAA4AAapuNhANDg0PKA8NDigPDQ8oDg0PDQ4pDg0PDQ4pDikODQ8NDg0PDQ4NDw0ODQ8NDikODQ8oDw0ODQ8NDg0PKA8NDg0PKA8MDygPKA8NDikODQ8NDg0PDQ4pDikODQ8NDikODQ8ACX9uNw4NDw0OKQ4NDygPDA8oDw0ODQ8oDw0ODQ8oDygPDQ4NDw0ODQ8NDg0PDQ4NDygPDQ4pDg0PDQ4NDw0OKQ4NDw0OKA8NDikOKQ4NDygPDQ4NDw0ODQ8oDygPDQ4NDygPDQ4ADQUAAAAAAAAAAA=='
    receiver_input_xbox:
      friendly_name: "AVR Input Xbox"
      command_on: 'JgDiAAoADBETAAwbCwAMGw8ACphvNg8NDg0PKA8NDikODQ8oDw0ODQ8oDwwPDQ8oDygODQ8NDg0PDQ4NDw0ODQ8NDikODQ8oDw0ODQ8NDikOKQ4NDw0OKQ4NDygPKA8MDygPDQ4NDw0ODQ8oDygPKA8NDikODQ8ACX9vNg4NDw0OKQ4NDygPDQ4oDw0PDA8oDw0ODQ8oDygPDQ4NDw0ODQ8NDg0PDQ4NDygPDQ4pDg0PDQ4NDygPKA8MDw0PKA8MDygPKA8NDikODQ8NDg0PDQ4pDikOKQ4NDygPDA+1DgAGGAkADQUAAAAAAAA='
      command_off: 'JgDiAAoADBETAAwbCwAMGw8ACphvNg8NDg0PKA8NDikODQ8oDw0ODQ8oDwwPDQ8oDygODQ8NDg0PDQ4NDw0ODQ8NDikODQ8oDw0ODQ8NDikOKQ4NDw0OKQ4NDygPKA8MDygPDQ4NDw0ODQ8oDygPKA8NDikODQ8ACX9vNg4NDw0OKQ4NDygPDQ4oDw0PDA8oDw0ODQ8oDygPDQ4NDw0ODQ8NDg0PDQ4NDygPDQ4pDg0PDQ4NDygPKA8MDw0PKA8MDygPKA8NDikODQ8NDg0PDQ4pDikOKQ4NDygPDA+1DgAGGAkADQUAAAAAAAA='

# MQTT Switches - Sonoff
- platform: mqtt
  name: "Sonoff Cord 01"
  command_topic: "cmnd/sonoff01/POWER"
  state_topic: "stat/sonoff01/POWER"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  retain: "true"

- platform: mqtt
  name: "Sonoff Cord 02"
  command_topic: "cmnd/sonoff02/POWER"
  state_topic: "stat/sonoff02/POWER"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  retain: "true"

# - platform: template
  # switches:
    # garage_daryl:
      # value_template: '{% if is_state("sensor.daryls_garage_door", "closed") %}off{% else %}on{% endif %}'
      # turn_on:
        # service: script.turn_on
        # entity_id: script.trigger_daryls_garage_door
      # turn_off:
        # service: script.turn_on
        # entity_id: script.trigger_daryls_garage_door
      # entity_id: sensor.daryls_garage_door
      # friendly_name: "Daryl's Garage Door"

# - platform: template
  # switches:
    # garage_megan:
      # value_template: '{% if is_state("sensor.megans_garage_door", "closed") %}off{% else %}on{% endif %}'
      # turn_on:
        # service: script.turn_on
        # entity_id: script.trigger_megans_garage_door
      # turn_off:
        # service: script.turn_on
        # entity_id: script.trigger_megans_garage_door
      # entity_id: sensor.megans_garage_door
      # friendly_name: "Megan's Garage Door"