alias: "Morning Routine - 6:55"
trigger:
  platform: time
  # Military time format.
  at: '06:55:00'
condition:
  condition: and
  conditions:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
    - condition: state
      entity_id: calendar.scheduling_nowork
      state: 'off'
action:
  - service: media_player.volume_set
    data_template:
      entity_id: media_player.coral_bathroom_speaker
      volume_level: 0.75
  - service: media_player.play_media
    data_template:
      entity_id: media_player.coral_bathroom_speaker
      media_content_id: http://hassio.s3.amazonaws.com/audio/computer-magic-5s.mp3
      #media_content_id: '{{ ["https://hassio.s3.amazonaws.com/audio/harp-strumming-5s.mp3", "https://hassio.s3.amazonaws.com/audio/triumphal-fanfare-4s.mp3", "https://hassio.s3.amazonaws.com/audio/news-intro-5-25s.mp3"] | random }}'
      media_content_type: MUSIC
  - delay: 0:00:07
  - service: tts.google_say
    entity_id: media_player.coral_bathroom_speaker
    data_template:
      message: >
        '{{ [
        "Good morning, Megan. Just wanted you to know that it's 6:55.",
        "6:55, Megan. Got your ducks in a row?",
        "Yo. It's 5 minutes until 7. Do stuff."
        ] | random }}'