############################################################
# Turns off under-cabinet lighting when no motion detected #
############################################################

alias: "Under-Cabinet Lights no Motion"
trigger:
  platform: state
  entity_id: sensor.kitchen_motion
  to: 'inactive'
  for:
    minutes: 2
action:
  service: light.turn_off
  data:
    entity_id: light.under_cabinet_lighting