########################################################
# Turns on under-cabinet lighting when motion detected #
########################################################

alias: "Under-Cabinet Lights with Motion"
trigger:
  platform: state
  entity_id: sensor.kitchen_motion
  to: 'active'
action:
  service: light.turn_on
  data:
    entity_id: light.under_cabinet_lighting