############################################################
# Alerts Megan that Daryl is at Walmart, give her actions  #
############################################################

alias: "Tell Megan when Daryl is at Walmart"
trigger:
  platform: state
  entity_id: device_tracker.mixpix405_2xl
  to: 'Walmart'
action:
  service: notify.html5
  data:
    message: "{{ as_timestamp(now()) | timestamp_custom('%I:%M%p', true) }} - Need anything? Tap yes, then update the list."
    title: "Daryl is at Walmart"
    target: "Megan's Pixel 2"
    data:
      actions:
        - action: "walmart_need"
          title: "Yes"
          icon: "/local/icons/checkbox-marked-circle-outline_hab.png"
        - action: "walmart_noneed"
          title: "Nope"
          icon: "/local/icons/close-circle-outline_hab.png"